Merged PR 14873847: Clang: Replace FIELD_OFFSET with offsetof.
Many errors for example:
```
  kdnetinterface.h:430:10: error: static_assert expression is not an integral
      constant expression
  C_ASSERT((FIELD_OFFSET(DEBUG_NET_PARAMETERS, HostMac) & 0x3) == 0);
```
Because `FIELD_OFFSET` is not constant. Replace with `offsetof`.

Related work items: #57987809, #60275790