Merged PR 14858692: Clang: Emcl: Name members.
```
Emcl.h:191:5: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
    EFI_EMCL_PROTOCOL;
    ^~~~~~~~~~~~~~~~~
```
Name it Base, use it.
Use it instead of casting also.
C++ would help here. :)

Related work items: #54710354, #60275790